// AUTO-GENERATED by scripts/generate-mcp-api-map.ts - DO NOT EDIT BY HAND.
// Re-generate with `pnpm mcp:api-map` (also runs before dev and build).
// 306 routes included, 74 excluded (see features/mcp/server/api-policy.ts).
import type { ApiRouteEntry } from "./api-catalog.types"

export const API_ROUTES: readonly ApiRouteEntry[] = [
  {
    path: "/api/analytics",
    methods: { GET: { permissions: ["analytics:read"], guard: "withAuth" } },
    load: () => import("@/app/api/analytics/route"),
  },
  {
    path: "/api/announcements/[id]",
    methods: {
      PATCH: {
        body: '{ title: string, body: string, category: string, priority?: "LOW"|"NORMAL"|"HIGH", isPublished?: boolean, expiresAt?: string }',
        permissions: ["announcement:write"],
        guard: "withAuth",
      },
      DELETE: { permissions: ["announcement:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/announcements/[id]/route"),
  },
  {
    path: "/api/announcements",
    methods: {
      GET: {
        query: ["month", "year", "category", "limit"],
        permissions: ["announcement:write"],
        guard: "withSession",
      },
      POST: {
        body: '{ title: string, body: string, category: string, priority?: "LOW"|"NORMAL"|"HIGH", isPublished?: boolean, expiresAt?: string }',
        permissions: ["announcement:write"],
        guard: "withAuth",
      },
    },
    load: () => import("@/app/api/announcements/route"),
  },
  {
    path: "/api/attendance/[id]",
    methods: {
      GET: { permissions: ["attendance:write"], guard: "withSession" },
      PATCH: { permissions: ["attendance:write"], guard: "withAuth" },
      DELETE: { permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/[id]/route"),
  },
  {
    path: "/api/attendance/devices/[id]/events",
    methods: {
      GET: { query: ["days", "major"], permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/devices/[id]/events/route"),
  },
  {
    path: "/api/attendance/devices/[id]",
    methods: {
      GET: { permissions: ["attendance:write"], guard: "withAuth" },
      PATCH: { permissions: ["attendance:write"], guard: "withAuth" },
      DELETE: { permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/devices/[id]/route"),
  },
  {
    path: "/api/attendance/devices/[id]/sync",
    methods: {
      POST: { query: ["employeeNo", "full"], permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/devices/[id]/sync/route"),
  },
  {
    path: "/api/attendance/devices/[id]/test",
    methods: { POST: { permissions: ["attendance:write"], guard: "withAuth" } },
    load: () => import("@/app/api/attendance/devices/[id]/test/route"),
  },
  {
    path: "/api/attendance/devices",
    methods: {
      GET: { permissions: ["attendance:write"], guard: "withAuth" },
      POST: { permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/devices/route"),
  },
  {
    path: "/api/attendance/directory/[employeeId]/calendar",
    methods: { GET: { query: ["month"], permissions: ["attendance:write"], guard: "withAuth" } },
    load: () => import("@/app/api/attendance/directory/[employeeId]/calendar/route"),
  },
  {
    path: "/api/attendance/directory",
    methods: {
      GET: { query: ["from", "to"], permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/directory/route"),
  },
  {
    path: "/api/attendance/employees/summary",
    methods: { GET: { permissions: ["attendance:write"], guard: "withAuth" } },
    load: () => import("@/app/api/attendance/employees/summary/route"),
  },
  {
    path: "/api/attendance/export",
    methods: {
      GET: {
        query: ["employeeId", "status", "dateFrom", "dateTo"],
        file: true,
        permissions: ["attendance:write"],
        guard: "withAuth",
      },
    },
    load: () => import("@/app/api/attendance/export/route"),
  },
  {
    path: "/api/attendance/floating-holidays/requests/[id]",
    methods: {
      PATCH: {
        body: '{ action: "APPROVE" | "REJECT", rejectionReason?: string }',
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/attendance/floating-holidays/requests/[id]/route"),
  },
  {
    path: "/api/attendance/floating-holidays/requests",
    methods: { GET: { query: ["status", "page", "limit"], guard: "withSession" } },
    load: () => import("@/app/api/attendance/floating-holidays/requests/route"),
  },
  {
    path: "/api/attendance/floating-holidays",
    methods: {
      GET: { query: ["year"], guard: "withSession" },
      POST: { guard: "withSession" },
      DELETE: { query: ["holidayId"], guard: "withSession" },
    },
    load: () => import("@/app/api/attendance/floating-holidays/route"),
  },
  {
    path: "/api/attendance/holidays/[id]",
    methods: {
      PATCH: { permissions: ["holiday:write"], guard: "withAuth" },
      DELETE: { permissions: ["holiday:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/holidays/[id]/route"),
  },
  {
    path: "/api/attendance/holidays",
    methods: {
      GET: { query: ["year"], permissions: ["attendance:read"], guard: "withAuth" },
      POST: { permissions: ["holiday:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/holidays/route"),
  },
  {
    path: "/api/attendance/me/calendar",
    methods: { GET: { query: ["month"], guard: "withSession" } },
    load: () => import("@/app/api/attendance/me/calendar/route"),
  },
  {
    path: "/api/attendance/me",
    methods: { GET: { query: ["days", "status", "page", "limit"], guard: "withSession" } },
    load: () => import("@/app/api/attendance/me/route"),
  },
  {
    path: "/api/attendance",
    methods: {
      GET: {
        query: ["employeeId", "status", "dateFrom", "dateTo", "page", "limit"],
        permissions: ["attendance:write"],
        guard: "withAuth",
      },
      POST: { permissions: ["attendance:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/attendance/route"),
  },
  {
    path: "/api/attendance/summary",
    methods: {
      GET: {
        query: ["employeeId", "month", "year"],
        permissions: ["attendance:write"],
        guard: "withAuth",
      },
    },
    load: () => import("@/app/api/attendance/summary/route"),
  },
  {
    path: "/api/attendance/sync",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/attendance/sync/route"),
  },
  {
    path: "/api/audit-log",
    methods: {
      GET: {
        query: ["page", "limit", "module", "actorId", "action", "dateFrom", "dateTo"],
        permissions: ["audit:read"],
        guard: "withAuth",
      },
    },
    load: () => import("@/app/api/audit-log/route"),
  },
  {
    path: "/api/birthdays",
    methods: { GET: { query: ["year", "days"], guard: "withSession" } },
    load: () => import("@/app/api/birthdays/route"),
  },
  {
    path: "/api/birthdays/wish",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/birthdays/wish/route"),
  },
  {
    path: "/api/careers/[id]",
    methods: {
      PATCH: {
        body: "{ code?: string, title?: string, slug?: any, jobsLabel?: string, tone?: any, order?: number, status?: any }",
        guard: "withErrorHandler",
      },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/careers/[id]/route"),
  },
  {
    path: "/api/careers/openings/[id]",
    methods: {
      PATCH: {
        body: "{ roleId?: string, label?: string, order?: number, status?: any }",
        guard: "withErrorHandler",
      },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/careers/openings/[id]/route"),
  },
  {
    path: "/api/careers/openings",
    methods: {
      POST: {
        body: "{ roleId: string, label: string, order?: number, status?: any }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/careers/openings/route"),
  },
  {
    path: "/api/careers/roles/[id]",
    methods: {
      PATCH: {
        body: "{ subDepartmentId?: string, title?: string, slug?: any, meta?: string, summary?: string, intro?: string, jobEssence?: string, keyRequirements?: string[], order?: number, status?: any }",
        guard: "withErrorHandler",
      },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/careers/roles/[id]/route"),
  },
  {
    path: "/api/careers/roles",
    methods: {
      POST: {
        body: "{ subDepartmentId: string, title: string, slug: any, meta?: string, summary?: string, intro?: string, jobEssence?: string, keyRequirements?: string[], order?: number, status?: any }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/careers/roles/route"),
  },
  {
    path: "/api/careers",
    methods: {
      GET: { guard: "withErrorHandler" },
      POST: {
        body: "{ code: string, title: string, slug: any, jobsLabel: string, tone?: any, order?: number, status?: any }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/careers/route"),
  },
  {
    path: "/api/careers/sub-departments/[id]",
    methods: {
      PATCH: {
        body: "{ groupId?: string, title?: string, slug?: any, jobsLabel?: string, tone?: any, order?: number, status?: any }",
        guard: "withErrorHandler",
      },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/careers/sub-departments/[id]/route"),
  },
  {
    path: "/api/careers/sub-departments",
    methods: {
      POST: {
        body: "{ groupId: string, title: string, slug: any, jobsLabel: string, tone?: any, order?: number, status?: any }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/careers/sub-departments/route"),
  },
  {
    path: "/api/chat/attachments/[attachmentId]/file",
    methods: { GET: { query: ["download"], file: true } },
    load: () => import("@/app/api/chat/attachments/[attachmentId]/file/route"),
  },
  {
    path: "/api/chat/contacts",
    methods: { GET: { query: ["search"], guard: "withSession" } },
    load: () => import("@/app/api/chat/contacts/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/attachments",
    methods: { POST: { upload: true, guard: "withSession" } },
    load: () => import("@/app/api/chat/conversations/[conversationId]/attachments/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/cards",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/chat/conversations/[conversationId]/cards/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/messages",
    methods: {
      GET: { query: ["before", "limit"], guard: "withSession" },
      POST: { body: "{ body: string, replyToId?: string }", guard: "withSession" },
    },
    load: () => import("@/app/api/chat/conversations/[conversationId]/messages/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/pin",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/chat/conversations/[conversationId]/pin/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/pinned",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/chat/conversations/[conversationId]/pinned/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/read",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/chat/conversations/[conversationId]/read/route"),
  },
  {
    path: "/api/chat/conversations/[conversationId]/search",
    methods: { GET: { query: ["q"], guard: "withSession" } },
    load: () => import("@/app/api/chat/conversations/[conversationId]/search/route"),
  },
  {
    path: "/api/chat/conversations",
    methods: {
      GET: { guard: "withSession" },
      POST: { body: "{ employeeId: string }", guard: "withSession" },
    },
    load: () => import("@/app/api/chat/conversations/route"),
  },
  {
    path: "/api/chat/messages/[messageId]/pin",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/chat/messages/[messageId]/pin/route"),
  },
  {
    path: "/api/chat/messages/[messageId]/react",
    methods: { POST: { body: "{ conversationId: string, emoji: string }", guard: "withSession" } },
    load: () => import("@/app/api/chat/messages/[messageId]/react/route"),
  },
  {
    path: "/api/chat/messages/[messageId]",
    methods: {
      PATCH: { body: "{ body: string }", guard: "withSession" },
      DELETE: { query: ["scope"], guard: "withSession" },
    },
    load: () => import("@/app/api/chat/messages/[messageId]/route"),
  },
  {
    path: "/api/chat/search",
    methods: { GET: { query: ["q"], guard: "withSession" } },
    load: () => import("@/app/api/chat/search/route"),
  },
  {
    path: "/api/chat/unread",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/chat/unread/route"),
  },
  {
    path: "/api/clearances/count",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/clearances/count/route"),
  },
  {
    path: "/api/clearances",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/clearances/route"),
  },
  {
    path: "/api/clients/[id]/activity",
    methods: {
      GET: { query: ["page", "limit"], permissions: ["client:read"], guard: "withClient" },
    },
    load: () => import("@/app/api/clients/[id]/activity/route"),
  },
  {
    path: "/api/clients/[id]/contacts/[contactId]",
    methods: { PATCH: { permissions: ["client:write"], guard: "withClient" } },
    load: () => import("@/app/api/clients/[id]/contacts/[contactId]/route"),
  },
  {
    path: "/api/clients/[id]/contacts",
    methods: { POST: { permissions: ["client:write"], guard: "withClient" } },
    load: () => import("@/app/api/clients/[id]/contacts/route"),
  },
  {
    path: "/api/clients/[id]/grants/[grantId]",
    methods: {
      PATCH: { permissions: ["client:write"], guard: "withClient" },
      DELETE: { permissions: ["client:write"], guard: "withClient" },
    },
    load: () => import("@/app/api/clients/[id]/grants/[grantId]/route"),
  },
  {
    path: "/api/clients/[id]/grants",
    methods: { POST: { permissions: ["client:write"], guard: "withClient" } },
    load: () => import("@/app/api/clients/[id]/grants/route"),
  },
  {
    path: "/api/clients/[id]",
    methods: {
      GET: { permissions: ["client:read"], guard: "withClient" },
      PATCH: { permissions: ["client:write"], guard: "withClient" },
      DELETE: { permissions: ["client:write"], guard: "withClient" },
    },
    load: () => import("@/app/api/clients/[id]/route"),
  },
  {
    path: "/api/clients",
    methods: {
      GET: { permissions: ["client:read"], guard: "withAuth" },
      POST: {
        body: "{ name: string, status?: enum, industry: any, website: any, email?: string, phone: any, address: any, taxId: any, notes: any, ownerId?: string }",
        permissions: ["client:write"],
        guard: "withAuth",
      },
    },
    load: () => import("@/app/api/clients/route"),
  },
  {
    path: "/api/dashboard/me",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/dashboard/me/route"),
  },
  {
    path: "/api/dashboard/stats",
    methods: { GET: { permissions: ["dashboard:read"], guard: "withAuth" } },
    load: () => import("@/app/api/dashboard/stats/route"),
  },
  {
    path: "/api/departments/[id]",
    methods: {
      GET: { guard: "withErrorHandler" },
      PATCH: {
        body: "{ name?: string, parentId?: string | null, headId?: string | null, isActive?: boolean, careersTone?: string | null, careersJobsLabel?: string | null }",
        guard: "withErrorHandler",
      },
      DELETE: { query: ["permanent"], guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/departments/[id]/route"),
  },
  {
    path: "/api/departments",
    methods: {
      GET: { query: ["includeInactive"], guard: "withErrorHandler" },
      POST: { body: "{ name: string, parentId?: string | null }", guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/departments/route"),
  },
  {
    path: "/api/designations/[id]",
    methods: {
      PATCH: {
        body: "{ title?: string, level?: number, isActive?: boolean }",
        guard: "withErrorHandler",
      },
      DELETE: { query: ["permanent"], guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/designations/[id]/route"),
  },
  {
    path: "/api/designations",
    methods: {
      GET: { query: ["includeInactive"], guard: "withErrorHandler" },
      POST: { body: "{ title: string, level: number }", guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/designations/route"),
  },
  {
    path: "/api/document-requests/[id]",
    methods: { PATCH: { permissions: ["document:write"], guard: "withSession" } },
    load: () => import("@/app/api/document-requests/[id]/route"),
  },
  {
    path: "/api/document-requests",
    methods: {
      GET: {
        query: ["employeeId", "status"],
        permissions: ["document:write"],
        guard: "withSession",
      },
      POST: { permissions: ["document:write"], guard: "withSession" },
    },
    load: () => import("@/app/api/document-requests/route"),
  },
  {
    path: "/api/documents/[id]",
    methods: {
      GET: { query: ["download"], file: true, guard: "withErrorHandler" },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/documents/[id]/route"),
  },
  {
    path: "/api/documents",
    methods: {
      GET: { query: ["category", "page", "limit"], guard: "withErrorHandler" },
      POST: { upload: true, guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/documents/route"),
  },
  {
    path: "/api/employees/[id]/activate",
    methods: { POST: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/[id]/activate/route"),
  },
  {
    path: "/api/employees/[id]/card",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/[id]/card/route"),
  },
  {
    path: "/api/employees/[id]/deactivate",
    methods: { POST: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/[id]/deactivate/route"),
  },
  {
    path: "/api/employees/[id]/documents/[docId]",
    methods: {
      GET: { query: ["download"], file: true, guard: "withErrorHandler" },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/employees/[id]/documents/[docId]/route"),
  },
  {
    path: "/api/employees/[id]/documents",
    methods: {
      GET: { guard: "withErrorHandler" },
      POST: { upload: true, guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/employees/[id]/documents/route"),
  },
  {
    path: "/api/employees/[id]/photo",
    methods: {
      GET: { file: true, guard: "withSession" },
      POST: { upload: true, guard: "withSession" },
      PUT: { guard: "withSession" },
      DELETE: { guard: "withSession" },
    },
    load: () => import("@/app/api/employees/[id]/photo/route"),
  },
  {
    path: "/api/employees/[id]/roles",
    methods: { PUT: { permissions: ["role:write"], guard: "withAuth" } },
    load: () => import("@/app/api/employees/[id]/roles/route"),
  },
  {
    path: "/api/employees/[id]",
    methods: {
      GET: { guard: "withErrorHandler" },
      PATCH: {
        body: '{ employeeNo?: string, firstName?: string, lastName?: string, email?: string, personalEmail?: string, phone?: string, personalPhone?: string, dateOfBirth?: string, gender?: "MALE"|"FEMALE"|"OTHER"|"PREFER_NOT_TO_SAY", nationality?: string, bloodGroup?: string, departmentId?: string, designationId?: string, jobRoleId?: union, roleId?: string, managerId?: string, dottedManagerId?: string, employmentType?: "FULL_TIME"|"PART_TIME"|"CONTRACT"|"INTERN", dateOfJoining?: string, probationEndDate?: string, status?: "ACTIVE"|"ON_LEAVE"|"SUSPENDED"|"RESIGNED"|"TERMINATED", resignationDate?: string, lastWorkingDate?: string, deviceId?: string, onProbation?: boolean, probationMonths?: any, workLocation?: string, currentAddress?: any, permanentAddress?: any, emergencyContact?: any, password?: string, mustChangePassword?: boolean, gmailAppPassword?: any }',
        guard: "withErrorHandler",
      },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/employees/[id]/route"),
  },
  {
    path: "/api/employees/[id]/task-access",
    methods: {
      GET: { permissions: ["employee:write"], guard: "withAuth" },
      PATCH: { permissions: ["employee:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/employees/[id]/task-access/route"),
  },
  {
    path: "/api/employees/bulk-terminate",
    methods: { POST: { body: "{ ids?: string[] }", guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/bulk-terminate/route"),
  },
  {
    path: "/api/employees/check-email",
    methods: { GET: { query: ["email", "excludeId"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/check-email/route"),
  },
  {
    path: "/api/employees/codes",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/codes/route"),
  },
  {
    path: "/api/employees/org-chart",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/employees/org-chart/route"),
  },
  {
    path: "/api/employees",
    methods: {
      GET: {
        query: [
          "search",
          "departmentId",
          "designationId",
          "status",
          "employmentType",
          "page",
          "limit",
        ],
        guard: "withErrorHandler",
      },
      POST: {
        body: '{ employeeNo?: string, firstName: string, lastName: string, email: string, personalEmail?: string, phone?: string, personalPhone?: string, dateOfBirth?: string, gender?: "MALE"|"FEMALE"|"OTHER"|"PREFER_NOT_TO_SAY", nationality?: string, bloodGroup?: string, departmentId?: string, designationId?: string, jobRoleId?: union, roleId?: string, managerId?: string, dottedManagerId?: string, employmentType?: "FULL_TIME"|"PART_TIME"|"CONTRACT"|"INTERN", dateOfJoining?: string, probationEndDate?: string, status?: "ACTIVE"|"ON_LEAVE"|"SUSPENDED"|"RESIGNED"|"TERMINATED", resignationDate?: string, lastWorkingDate?: string, deviceId?: string, onProbation?: boolean, probationMonths: any, workLocation?: string, currentAddress: any, permanentAddress: any, emergencyContact: any, password?: string, mustChangePassword?: boolean, gmailAppPassword: any }',
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/employees/route"),
  },
  {
    path: "/api/exit-clearance/serving-notice",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/exit-clearance/serving-notice/route"),
  },
  {
    path: "/api/gallery/albums/[albumId]/photos",
    methods: { POST: { upload: true, guard: "withSession" } },
    load: () => import("@/app/api/gallery/albums/[albumId]/photos/route"),
  },
  {
    path: "/api/gallery/albums/[albumId]",
    methods: {
      GET: { guard: "withSession" },
      DELETE: { permissions: ["gallery:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/gallery/albums/[albumId]/route"),
  },
  {
    path: "/api/gallery/albums",
    methods: {
      GET: { query: ["search"], guard: "withSession" },
      POST: {
        body: "{ title: string, description?: string, eventDate?: string }",
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/gallery/albums/route"),
  },
  {
    path: "/api/gallery/photos/[photoId]/file",
    methods: { GET: { query: ["variant", "download"], file: true } },
    load: () => import("@/app/api/gallery/photos/[photoId]/file/route"),
  },
  {
    path: "/api/gallery/photos/[photoId]",
    methods: { DELETE: { guard: "withSession" } },
    load: () => import("@/app/api/gallery/photos/[photoId]/route"),
  },
  {
    path: "/api/hr-checklists/[id]/cancel",
    methods: { POST: { body: "{ reason?: string }", guard: "withSession" } },
    load: () => import("@/app/api/hr-checklists/[id]/cancel/route"),
  },
  {
    path: "/api/hr-checklists/[id]/complete-exit",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/hr-checklists/[id]/complete-exit/route"),
  },
  {
    path: "/api/hr-checklists/[id]/complete",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/hr-checklists/[id]/complete/route"),
  },
  {
    path: "/api/hr-checklists/[id]/items",
    methods: {
      POST: {
        body: '{ sectionTitle: string, text: string, helpText?: string, itemKind?: "TASK"|"CLEARANCE", assigneeId?: string, isRequired?: boolean, dueDate?: string }',
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/hr-checklists/[id]/items/route"),
  },
  {
    path: "/api/hr-checklists/[id]",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/hr-checklists/[id]/route"),
  },
  {
    path: "/api/hr-checklists/items/[itemId]/assignee",
    methods: { PATCH: { body: "{ assigneeId: string }", guard: "withSession" } },
    load: () => import("@/app/api/hr-checklists/items/[itemId]/assignee/route"),
  },
  {
    path: "/api/hr-checklists/items/[itemId]",
    methods: { PATCH: { body: "{ done: boolean, note?: string }", guard: "withSession" } },
    load: () => import("@/app/api/hr-checklists/items/[itemId]/route"),
  },
  {
    path: "/api/hr-checklists",
    methods: {
      GET: { query: ["kind", "status", "search", "page", "limit"], guard: "withSession" },
      POST: { body: '{ employeeId?: string, kind?: "ONBOARDING" | "EXIT" }', guard: "withSession" },
    },
    load: () => import("@/app/api/hr-checklists/route"),
  },
  {
    path: "/api/job-roles/[id]",
    methods: {
      PATCH: {
        body: "{ name?: string, departmentId?: string, isActive?: boolean }",
        guard: "withErrorHandler",
      },
      DELETE: { query: ["permanent"], guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/job-roles/[id]/route"),
  },
  {
    path: "/api/job-roles",
    methods: {
      GET: { query: ["departmentId", "includeInactive"], guard: "withErrorHandler" },
      POST: { body: "{ name: string, departmentId: string }", guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/job-roles/route"),
  },
  {
    path: "/api/joinee-scorecards/[id]/days/[day]",
    methods: { PATCH: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/joinee-scorecards/[id]/days/[day]/route"),
  },
  {
    path: "/api/joinee-scorecards/[id]",
    methods: {
      PATCH: {
        body: "{ hrSpocId?: string | null, managerObservations?: string | null, hrObservations?: string | null, recommendation?: string | null }",
        guard: "withErrorHandler",
      },
      DELETE: { guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/joinee-scorecards/[id]/route"),
  },
  {
    path: "/api/joinee-scorecards",
    methods: {
      GET: { query: ["employeeId"], guard: "withErrorHandler" },
      POST: {
        body: "{ employeeId?: string, hrSpocId?: string | null }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/joinee-scorecards/route"),
  },
  {
    path: "/api/leave/apply/preview",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/leave/apply/preview/route"),
  },
  {
    path: "/api/leave/balances/directory",
    methods: { GET: { query: ["year"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/leave/balances/directory/route"),
  },
  {
    path: "/api/leave/balances/resync",
    methods: { POST: { body: "{ year?: number }", guard: "withErrorHandler" } },
    load: () => import("@/app/api/leave/balances/resync/route"),
  },
  {
    path: "/api/leave/balances",
    methods: {
      GET: { query: ["employeeId", "year"], guard: "withErrorHandler" },
      POST: {
        body: "{ employeeId: string, leaveTypeId: string, year: number, allocated: number, carried?: number }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/leave/balances/route"),
  },
  {
    path: "/api/leave/day-status",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/leave/day-status/route"),
  },
  {
    path: "/api/leave/decision/polish",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/leave/decision/polish/route"),
  },
  {
    path: "/api/leave/decision/preview",
    methods: { GET: { query: ["requestId"], guard: "withSession" } },
    load: () => import("@/app/api/leave/decision/preview/route"),
  },
  {
    path: "/api/leave/my-team",
    methods: { GET: { query: ["status", "page", "limit"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/leave/my-team/route"),
  },
  {
    path: "/api/leave/policies",
    methods: {
      GET: { guard: "withErrorHandler" },
      PUT: {
        body: "{ entries: Array<{ employmentType: string; leaveTypeId: string; daysPerYear: number | null  }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/leave/policies/route"),
  },
  {
    path: "/api/leave/polish-reason",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/leave/polish-reason/route"),
  },
  {
    path: "/api/leave/requests/[id]",
    methods: {
      PATCH: {
        body: '{ action: "CANCEL" | "APPROVE" | "REJECT", rejectionReason?: string, emailBody?: string }',
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/leave/requests/[id]/route"),
  },
  {
    path: "/api/leave/requests",
    methods: {
      GET: {
        query: ["status", "employeeId", "leaveTypeId", "from", "to", "page", "limit"],
        guard: "withErrorHandler",
      },
      POST: {
        body: "{ leaveTypeId: string, startDate: string, endDate: string, reason?: string, isHalfDay?: boolean, emailBody?: string, emailSubject?: string }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/leave/requests/route"),
  },
  {
    path: "/api/leave/team",
    methods: { GET: { query: ["status", "page", "limit"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/leave/team/route"),
  },
  {
    path: "/api/leave/types/[id]",
    methods: {
      PATCH: { guard: "withErrorHandler" },
      DELETE: { query: ["permanent"], guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/leave/types/[id]/route"),
  },
  {
    path: "/api/leave/types/eligible",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/leave/types/eligible/route"),
  },
  {
    path: "/api/leave/types",
    methods: { GET: { guard: "withErrorHandler" }, POST: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/leave/types/route"),
  },
  {
    path: "/api/message-polls/[pollId]/vote",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/message-polls/[pollId]/vote/route"),
  },
  {
    path: "/api/notifications/inbox",
    methods: {
      GET: { query: ["page", "limit", "unread"], guard: "withSession" },
      PATCH: { guard: "withSession" },
      DELETE: { query: ["id", "all"], guard: "withSession" },
    },
    load: () => import("@/app/api/notifications/inbox/route"),
  },
  {
    path: "/api/notifications/task-reminders",
    methods: {
      GET: { guard: "withSession" },
      PATCH: {
        body: "{ enabled: boolean, leadMinutes: any, reminderCount: any, repeatEveryMinutes: any }",
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/notifications/task-reminders/route"),
  },
  {
    path: "/api/notifications/templates",
    methods: {
      GET: { permissions: ["email_template:read"], guard: "withAuth" },
      POST: {
        body: "{ slug: any, name: string, subject: string, bodyHtml: string, bodyText?: string, mergeFields?: string[], isActive?: boolean, trigger?: string }",
        permissions: ["email_template:write"],
        guard: "withAuth",
      },
      PATCH: { permissions: ["email_template:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/notifications/templates/route"),
  },
  {
    path: "/api/payroll/me/[id]",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/payroll/me/[id]/route"),
  },
  {
    path: "/api/payroll/me",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/payroll/me/route"),
  },
  {
    path: "/api/payroll/records/[id]",
    methods: {
      GET: { permissions: ["payroll:read", "payroll:write"], guard: "withAuth" },
      PATCH: { permissions: ["payroll:process"], guard: "withAuth" },
      DELETE: { permissions: ["payroll:process"], guard: "withAuth" },
    },
    load: () => import("@/app/api/payroll/records/[id]/route"),
  },
  {
    path: "/api/payroll/records",
    methods: {
      GET: {
        query: ["month", "year", "status", "employeeId", "search", "page", "limit"],
        permissions: ["payroll:read", "payroll:write"],
        guard: "withAuth",
      },
      POST: { permissions: ["payroll:process"], guard: "withAuth" },
    },
    load: () => import("@/app/api/payroll/records/route"),
  },
  {
    path: "/api/payroll/salary-structures/[id]",
    methods: {
      GET: { permissions: ["payroll:write"], guard: "withAuth" },
      PATCH: { permissions: ["payroll:write"], guard: "withAuth" },
      DELETE: { permissions: ["payroll:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/payroll/salary-structures/[id]/route"),
  },
  {
    path: "/api/payroll/salary-structures",
    methods: {
      GET: { permissions: ["payroll:read", "payroll:write"], guard: "withAuth" },
      POST: { permissions: ["payroll:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/payroll/salary-structures/route"),
  },
  {
    path: "/api/payroll/summary",
    methods: {
      GET: { query: ["month", "year"], permissions: ["payroll:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/payroll/summary/route"),
  },
  {
    path: "/api/performance/evaluations/[id]",
    methods: {
      GET: { guard: "withSession" },
      PATCH: { permissions: ["performance:review"], guard: "withSession" },
      DELETE: { permissions: ["performance:review"], guard: "withSession" },
    },
    load: () => import("@/app/api/performance/evaluations/[id]/route"),
  },
  {
    path: "/api/performance/evaluations/bulk-delete",
    methods: { POST: { body: "{ ids?: string[] }", guard: "withErrorHandler" } },
    load: () => import("@/app/api/performance/evaluations/bulk-delete/route"),
  },
  {
    path: "/api/performance/evaluations/generate",
    methods: { POST: { permissions: ["performance:review"], guard: "withSession" } },
    load: () => import("@/app/api/performance/evaluations/generate/route"),
  },
  {
    path: "/api/performance/evaluations",
    methods: {
      GET: {
        query: ["status", "period", "q", "page", "limit"],
        permissions: ["performance:review"],
        guard: "withSession",
      },
      POST: { permissions: ["performance:review"], guard: "withSession" },
    },
    load: () => import("@/app/api/performance/evaluations/route"),
  },
  {
    path: "/api/performance/kpi-profiles/[employeeId]",
    methods: {
      GET: { permissions: ["performance:review"], guard: "withAuth" },
      PUT: { permissions: ["performance:review"], guard: "withAuth" },
    },
    load: () => import("@/app/api/performance/kpi-profiles/[employeeId]/route"),
  },
  {
    path: "/api/performance/kpi-profiles",
    methods: { GET: { permissions: ["performance:review"], guard: "withAuth" } },
    load: () => import("@/app/api/performance/kpi-profiles/route"),
  },
  {
    path: "/api/permissions",
    methods: { GET: { permissions: ["role:read"], guard: "withAuth" } },
    load: () => import("@/app/api/permissions/route"),
  },
  {
    path: "/api/profile",
    methods: { GET: { guard: "withSession" }, PATCH: { guard: "withSession" } },
    load: () => import("@/app/api/profile/route"),
  },
  {
    path: "/api/projects/[id]/activity",
    methods: { GET: { query: ["limit", "key"], guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/activity/route"),
  },
  {
    path: "/api/projects/[id]/assignable-employees",
    methods: { GET: { guard: "withTeamStaffing" } },
    load: () => import("@/app/api/projects/[id]/assignable-employees/route"),
  },
  {
    path: "/api/projects/[id]/brand/analyse",
    methods: { POST: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/brand/analyse/route"),
  },
  {
    path: "/api/projects/[id]/brand/assets/[assetId]",
    methods: {
      GET: { file: true, guard: "withProjectAccess" },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/brand/assets/[assetId]/route"),
  },
  {
    path: "/api/projects/[id]/brand/assets",
    methods: { POST: { upload: true, guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/brand/assets/route"),
  },
  {
    path: "/api/projects/[id]/brand",
    methods: { GET: { guard: "withProjectAccess" }, PUT: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/brand/route"),
  },
  {
    path: "/api/projects/[id]/deliverables/[deliverableId]/events",
    methods: { GET: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/[deliverableId]/events/route"),
  },
  {
    path: "/api/projects/[id]/deliverables/[deliverableId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/[deliverableId]/route"),
  },
  {
    path: "/api/projects/[id]/deliverables/[deliverableId]/start",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/[deliverableId]/start/route"),
  },
  {
    path: "/api/projects/[id]/deliverables/[deliverableId]/status",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/[deliverableId]/status/route"),
  },
  {
    path: "/api/projects/[id]/deliverables/[deliverableId]/verify",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/[deliverableId]/verify/route"),
  },
  {
    path: "/api/projects/[id]/deliverables/plan",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/plan/route"),
  },
  {
    path: "/api/projects/[id]/deliverables",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/deliverables/route"),
  },
  {
    path: "/api/projects/[id]/drive/export",
    methods: { POST: { file: true, guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/drive/export/route"),
  },
  {
    path: "/api/projects/[id]/drive/file",
    methods: {
      PATCH: {
        body: "{ fileId: string, name?: string, folderId?: any }",
        guard: "withProjectAccess",
      },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/drive/file/route"),
  },
  {
    path: "/api/projects/[id]/drive/new",
    methods: {
      POST: {
        body: '{ kind?: "doc" | "sheet", name?: string, folderId?: string | null }',
        guard: "withProjectAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/drive/new/route"),
  },
  {
    path: "/api/projects/[id]/drive",
    methods: {
      GET: { guard: "withProjectAccess" },
      POST: { upload: true, guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/drive/route"),
  },
  {
    path: "/api/projects/[id]/drive/sync",
    methods: { POST: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/drive/sync/route"),
  },
  {
    path: "/api/projects/[id]/files",
    methods: { GET: { query: ["folder"], guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/files/route"),
  },
  {
    path: "/api/projects/[id]/folders/[folderId]",
    methods: {
      PATCH: { body: "{ name?: any, parentId?: any }", guard: "withProjectAccess" },
      DELETE: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/folders/[folderId]/route"),
  },
  {
    path: "/api/projects/[id]/folders",
    methods: {
      GET: { guard: "withProjectAccess" },
      POST: { body: "{ parentId?: any }", guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/folders/route"),
  },
  {
    path: "/api/projects/[id]/goals/[goalId]/reactivate",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/goals/[goalId]/reactivate/route"),
  },
  {
    path: "/api/projects/[id]/goals/[goalId]",
    methods: {
      PATCH: { guard: "withProjectAccess" },
      DELETE: { query: ["permanent", "reason"], guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/goals/[goalId]/route"),
  },
  {
    path: "/api/projects/[id]/goals/[goalId]/targets/[targetId]",
    methods: {
      PATCH: {
        doc: "sends only what changed: an omitted period is left alone, null clears it (back to standing). Both write to the goal's history.",
        guard: "withProjectAccess",
      },
      DELETE: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/goals/[goalId]/targets/[targetId]/route"),
  },
  {
    path: "/api/projects/[id]/goals/[goalId]/targets",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/goals/[goalId]/targets/route"),
  },
  {
    path: "/api/projects/[id]/goals/[goalId]/tasks",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/goals/[goalId]/tasks/route"),
  },
  {
    path: "/api/projects/[id]/goals",
    methods: {
      GET: { query: ["includeInactive"], guard: "withProjectAccess" },
      POST: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/goals/route"),
  },
  {
    path: "/api/projects/[id]/integration",
    methods: {
      GET: { query: ["days", "from", "to"], guard: "withProjectAccess" },
      POST: {
        body: "{ appId?: string, appSecret?: string, accessToken?: string, adAccountId?: string }",
        guard: "withProjectManager",
      },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/integration/route"),
  },
  {
    path: "/api/projects/[id]/integration/sync",
    methods: { POST: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/integration/sync/route"),
  },
  {
    path: "/api/projects/[id]/links/[linkId]",
    methods: {
      PATCH: {
        body: "{ title?: string, url?: any, folderId?: any, tag?: any, description?: string }",
        guard: "withProjectAccess",
      },
      DELETE: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/links/[linkId]/route"),
  },
  {
    path: "/api/projects/[id]/links",
    methods: {
      GET: { guard: "withProjectAccess" },
      POST: {
        body: "{ title: string, folderId?: any, tag?: any, description?: string }",
        guard: "withProjectAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/links/route"),
  },
  {
    path: "/api/projects/[id]/logo",
    methods: {
      GET: { file: true, guard: "withProjectAccess" },
      POST: { upload: true, guard: "withProjectManager" },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/logo/route"),
  },
  {
    path: "/api/projects/[id]/mailer/accounts/[mailerId]",
    methods: { PATCH: { guard: "withMailerAccess" }, DELETE: { guard: "withMailerAccess" } },
    load: () => import("@/app/api/projects/[id]/mailer/accounts/[mailerId]/route"),
  },
  {
    path: "/api/projects/[id]/mailer/accounts/[mailerId]/test",
    methods: { POST: { body: "{ to: string }", guard: "withMailerAccess" } },
    load: () => import("@/app/api/projects/[id]/mailer/accounts/[mailerId]/test/route"),
  },
  {
    path: "/api/projects/[id]/mailer/accounts",
    methods: { POST: { guard: "withMailerAccess" } },
    load: () => import("@/app/api/projects/[id]/mailer/accounts/route"),
  },
  {
    path: "/api/projects/[id]/mailer/campaigns/[campaignId]",
    methods: {
      GET: { guard: "withMailerAccess" },
      DELETE: {
        doc: "cancels (keeps the log of what went out); ?purge=1 removes the campaign and its log. Explicit, never inferred from status, so stopping a send can't erase its record.",
        query: ["purge"],
        guard: "withMailerAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/mailer/campaigns/[campaignId]/route"),
  },
  {
    path: "/api/projects/[id]/mailer/campaigns",
    methods: {
      POST: {
        body: '{ mailerId: string, name: string, subject: string, bodyHtml: string, bodyMode?: "RICH"|"HTML", templateId?: string, tags?: string[] }',
        guard: "withMailerAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/mailer/campaigns/route"),
  },
  {
    path: "/api/projects/[id]/mailer/images/[assetId]",
    methods: { DELETE: { guard: "withMailerAccess" } },
    load: () => import("@/app/api/projects/[id]/mailer/images/[assetId]/route"),
  },
  {
    path: "/api/projects/[id]/mailer/images",
    methods: { POST: { upload: true, guard: "withMailerAccess" } },
    load: () => import("@/app/api/projects/[id]/mailer/images/route"),
  },
  {
    path: "/api/projects/[id]/mailer/recipients/[recipientId]",
    methods: {
      PATCH: {
        doc: "toggles the subscription; unsubscribing is checked again at send time.",
        guard: "withMailerAccess",
      },
      DELETE: { guard: "withMailerAccess" },
    },
    load: () => import("@/app/api/projects/[id]/mailer/recipients/[recipientId]/route"),
  },
  {
    path: "/api/projects/[id]/mailer/recipients/bulk",
    methods: {
      POST: { body: "{ raw: string, tags?: string[] }", guard: "withMailerAccess" },
      DELETE: { guard: "withMailerAccess" },
    },
    load: () => import("@/app/api/projects/[id]/mailer/recipients/bulk/route"),
  },
  {
    path: "/api/projects/[id]/mailer/recipients/import",
    methods: {
      POST: {
        body: "{ rows: any, tags?: string[], tagExisting?: boolean }",
        guard: "withMailerAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/mailer/recipients/import/route"),
  },
  {
    path: "/api/projects/[id]/mailer/recipients",
    methods: {
      POST: {
        body: "{ email: string, name?: string, company?: string, tags?: string[], fields?: record }",
        guard: "withMailerAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/mailer/recipients/route"),
  },
  {
    path: "/api/projects/[id]/mailer",
    methods: { GET: { guard: "withMailerAccess" } },
    load: () => import("@/app/api/projects/[id]/mailer/route"),
  },
  {
    path: "/api/projects/[id]/mailer/templates/[templateId]",
    methods: {
      PATCH: {
        body: '{ name: string, subject: string, bodyHtml: string, bodyMode?: "RICH"|"HTML", isActive?: boolean }',
        guard: "withMailerAccess",
      },
      DELETE: { guard: "withMailerAccess" },
    },
    load: () => import("@/app/api/projects/[id]/mailer/templates/[templateId]/route"),
  },
  {
    path: "/api/projects/[id]/mailer/templates",
    methods: {
      POST: {
        body: '{ name: string, subject: string, bodyHtml: string, bodyMode?: "RICH"|"HTML", isActive?: boolean }',
        guard: "withMailerAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/mailer/templates/route"),
  },
  {
    path: "/api/projects/[id]/members/[memberId]/tasks",
    methods: { GET: { query: ["from", "to"], guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/members/[memberId]/tasks/route"),
  },
  {
    path: "/api/projects/[id]/members",
    methods: { GET: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/members/route"),
  },
  {
    path: "/api/projects/[id]/messages/[messageId]/attachments",
    methods: { POST: { upload: true, guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/[messageId]/attachments/route"),
  },
  {
    path: "/api/projects/[id]/messages/[messageId]/cards",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/[messageId]/cards/route"),
  },
  {
    path: "/api/projects/[id]/messages/[messageId]/react",
    methods: { POST: { body: "{ emoji?: string, replyId?: string }", guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/[messageId]/react/route"),
  },
  {
    path: "/api/projects/[id]/messages/[messageId]/replies/[replyId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/[messageId]/replies/[replyId]/route"),
  },
  {
    path: "/api/projects/[id]/messages/[messageId]/replies",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/[messageId]/replies/route"),
  },
  {
    path: "/api/projects/[id]/messages/[messageId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/[messageId]/route"),
  },
  {
    path: "/api/projects/[id]/messages",
    methods: {
      GET: { query: ["q"], guard: "withProjectAccess" },
      POST: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/messages/route"),
  },
  {
    path: "/api/projects/[id]/messages/unread",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/messages/unread/route"),
  },
  {
    path: "/api/projects/[id]/monitoring/assets/[assetId]",
    methods: {
      PATCH: {
        body: "{ kind: enum, name: string, provider?: string, url?: string, expiresAt: string, autoRenew?: boolean, paymentMethod?: string, paymentExpiresAt: any, ownerId?: string, notes?: string }",
        guard: "withProjectAccess",
      },
      DELETE: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/monitoring/assets/[assetId]/route"),
  },
  {
    path: "/api/projects/[id]/monitoring/assets",
    methods: {
      POST: {
        body: "{ kind: enum, name: string, provider?: string, url?: string, expiresAt: string, autoRenew?: boolean, paymentMethod?: string, paymentExpiresAt: any, ownerId?: string, notes?: string }",
        guard: "withProjectAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/monitoring/assets/route"),
  },
  {
    path: "/api/projects/[id]/monitoring/incidents/[incidentId]/ack",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/monitoring/incidents/[incidentId]/ack/route"),
  },
  {
    path: "/api/projects/[id]/monitoring/monitors/[monitorId]",
    methods: {
      PATCH: {
        body: "{ url: any, label?: string, ownerId?: string, isActive?: boolean }",
        guard: "withProjectAccess",
      },
      DELETE: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/monitoring/monitors/[monitorId]/route"),
  },
  {
    path: "/api/projects/[id]/monitoring/monitors",
    methods: {
      POST: {
        body: "{ url: any, label?: string, ownerId?: string, isActive?: boolean }",
        guard: "withProjectAccess",
      },
    },
    load: () => import("@/app/api/projects/[id]/monitoring/monitors/route"),
  },
  {
    path: "/api/projects/[id]/monitoring",
    methods: { GET: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/monitoring/route"),
  },
  {
    path: "/api/projects/[id]/passwords/[entryId]",
    methods: { PATCH: { guard: "withProjectManager" }, DELETE: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/passwords/[entryId]/route"),
  },
  {
    path: "/api/projects/[id]/passwords",
    methods: { GET: { guard: "withProjectManager" }, POST: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/passwords/route"),
  },
  {
    path: "/api/projects/[id]/progress",
    methods: { GET: { query: ["from", "to"], guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/progress/route"),
  },
  {
    path: "/api/projects/[id]/requirements/[requirementId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/requirements/[requirementId]/route"),
  },
  {
    path: "/api/projects/[id]/requirements",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/requirements/route"),
  },
  {
    path: "/api/projects/[id]/resources/[fileId]",
    methods: {
      GET: { query: ["download"], file: true, guard: "withProjectAccess" },
      DELETE: { guard: "withSession" },
      PATCH: {
        body: "{ tag?: any, fileName?: string, folderId?: any, isClientVisible?: boolean }",
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/projects/[id]/resources/[fileId]/route"),
  },
  {
    path: "/api/projects/[id]/resources",
    methods: {
      GET: { query: ["teamId", "category"], guard: "withProjectAccess" },
      POST: { upload: true, guard: "withSession" },
    },
    load: () => import("@/app/api/projects/[id]/resources/route"),
  },
  {
    path: "/api/projects/[id]",
    methods: {
      GET: { guard: "withProjectAccess" },
      PATCH: { guard: "withProjectManager" },
      DELETE: { permissions: ["project:delete"], guard: "withAuth" },
    },
    load: () => import("@/app/api/projects/[id]/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/ai",
    methods: {
      POST: { body: '{ task: "keywords"|"competitors"|"explain" }', guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/ai/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/backlinks",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: {
        body: '{ text: string, source?: "AWT"|"GSC"|"MANUAL", fullSnapshot?: boolean }',
        guard: "withProjectManager",
      },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/backlinks/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/competitors",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/competitors/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/content/[briefId]",
    methods: {
      PATCH: {
        body: '{ action?: "update"|"qa", url?: string, status?: "BRIEF"|"WRITING"|"REVIEW"|"PUBLISHED"|"MEASURED"|"PARKED", outline?: string[], angle?: string, notes?: string, publishedUrl?: string }',
        guard: "withProjectManager",
      },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/content/[briefId]/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/content",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { body: "{ keywordId?: string, targetQuery?: string }", guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/content/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/keywords/[keywordId]",
    methods: {
      PATCH: {
        body: '{ winnable?: boolean, businessValue?: number, intent?: "commercial"|"informational"|"branded"|"navigational"|"other", status?: "BACKLOG"|"IN_PROGRESS"|"PUBLISHED"|"PARKED", notes?: string }',
        guard: "withProjectManager",
      },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/keywords/[keywordId]/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/keywords",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/keywords/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/monitor",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/monitor/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/overview",
    methods: { GET: { query: ["end", "weeks"], permissions: ["project:read"], guard: "withAuth" } },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/overview/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]",
    methods: {
      PUT: {
        body: "{ label: string, domain: any, siteUrl: any, gaPropertyId?: string, moneyKeywords?: any, moneyPages?: any, competitors?: any, targetClicks?: number, targetPosition?: number, isActive?: boolean, isPrimary?: boolean }",
        guard: "withProjectManager",
      },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/scorecard",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/scorecard/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/setup",
    methods: { GET: { permissions: ["project:read"], guard: "withAuth" } },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/setup/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/sync",
    methods: { POST: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/sync/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/technical",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/technical/route"),
  },
  {
    path: "/api/projects/[id]/seo/[propertyId]/vitals",
    methods: {
      GET: { permissions: ["project:read"], guard: "withAuth" },
      POST: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/seo/[propertyId]/vitals/route"),
  },
  {
    path: "/api/projects/[id]/seo/rollup",
    methods: { GET: { permissions: ["project:read"], guard: "withAuth" } },
    load: () => import("@/app/api/projects/[id]/seo/rollup/route"),
  },
  {
    path: "/api/projects/[id]/seo",
    methods: {
      GET: { guard: "withProjectAccess" },
      POST: {
        body: "{ label: string, domain: any, siteUrl: any, gaPropertyId?: string, moneyKeywords?: any, moneyPages?: any, competitors?: any, targetClicks?: number, targetPosition?: number, isActive?: boolean, isPrimary?: boolean }",
        guard: "withProjectManager",
      },
    },
    load: () => import("@/app/api/projects/[id]/seo/route"),
  },
  {
    path: "/api/projects/[id]/seo/sync",
    methods: { POST: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/seo/sync/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/cells",
    methods: { PATCH: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/cells/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/columns/[columnId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/columns/[columnId]/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/columns",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/columns/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/history",
    methods: { GET: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/history/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/import",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/import/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/layout",
    methods: { PATCH: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/layout/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/rows/[rowId]",
    methods: { PATCH: { guard: "withProjectAccess" }, DELETE: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/rows/[rowId]/route"),
  },
  {
    path: "/api/projects/[id]/sheets/[sheetId]/rows",
    methods: { POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/sheets/[sheetId]/rows/route"),
  },
  {
    path: "/api/projects/[id]/sheets",
    methods: {
      GET: {
        doc: "returns tab names only (a calendar has one edition per month); grids come from /workbooks/[workbookId]. Any project member may create tabs; only DELETE (on [sheetId]) is restricted.",
        guard: "withProjectAccess",
      },
      POST: { guard: "withProjectAccess" },
    },
    load: () => import("@/app/api/projects/[id]/sheets/route"),
  },
  {
    path: "/api/projects/[id]/tasks",
    methods: {
      GET: { query: ["status", "assigneeId"], guard: "withProjectAccess" },
      POST: { guard: "withTeamStaffing" },
    },
    load: () => import("@/app/api/projects/[id]/tasks/route"),
  },
  {
    path: "/api/projects/[id]/teams/[teamId]/members/[memberId]/promote",
    methods: { PATCH: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/teams/[teamId]/members/[memberId]/promote/route"),
  },
  {
    path: "/api/projects/[id]/teams/[teamId]/members/[memberId]",
    methods: { DELETE: { guard: "withSession" } },
    load: () => import("@/app/api/projects/[id]/teams/[teamId]/members/[memberId]/route"),
  },
  {
    path: "/api/projects/[id]/teams/[teamId]/members",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withSession" } },
    load: () => import("@/app/api/projects/[id]/teams/[teamId]/members/route"),
  },
  {
    path: "/api/projects/[id]/teams/[teamId]",
    methods: {
      PATCH: {
        body: "{ name?: unknown, description?: unknown, managerId?: string | null }",
        guard: "withProjectManager",
      },
      DELETE: {},
    },
    load: () => import("@/app/api/projects/[id]/teams/[teamId]/route"),
  },
  {
    path: "/api/projects/[id]/teams/[teamId]/tasks",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withSession" } },
    load: () => import("@/app/api/projects/[id]/teams/[teamId]/tasks/route"),
  },
  {
    path: "/api/projects/[id]/teams",
    methods: {
      GET: { guard: "withProjectAccess" },
      POST: {
        doc: "refused. Every project has the same fixed teams (features/projects/lib/project-teams.ts), made with the project; nobody, admin included, adds one. Staff a team instead.",
      },
    },
    load: () => import("@/app/api/projects/[id]/teams/route"),
  },
  {
    path: "/api/projects/[id]/workbooks/[workbookId]/assign",
    methods: { POST: { guard: "withTeamStaffing" } },
    load: () => import("@/app/api/projects/[id]/workbooks/[workbookId]/assign/route"),
  },
  {
    path: "/api/projects/[id]/workbooks/[workbookId]",
    methods: {
      GET: { guard: "withProjectAccess" },
      PATCH: { guard: "withProjectAccess" },
      DELETE: { guard: "withProjectManager" },
    },
    load: () => import("@/app/api/projects/[id]/workbooks/[workbookId]/route"),
  },
  {
    path: "/api/projects/[id]/workbooks/[workbookId]/share",
    methods: { PATCH: { guard: "withProjectManager" } },
    load: () => import("@/app/api/projects/[id]/workbooks/[workbookId]/share/route"),
  },
  {
    path: "/api/projects/[id]/workbooks/[workbookId]/teams/[teamId]",
    methods: {
      PUT: { guard: "withWorkbookTeamContribute" },
      DELETE: { guard: "withWorkbookTeamAccess" },
    },
    load: () => import("@/app/api/projects/[id]/workbooks/[workbookId]/teams/[teamId]/route"),
  },
  {
    path: "/api/projects/[id]/workbooks/[workbookId]/teams",
    methods: { GET: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/workbooks/[workbookId]/teams/route"),
  },
  {
    path: "/api/projects/[id]/workbooks",
    methods: { GET: { guard: "withProjectAccess" }, POST: { guard: "withProjectAccess" } },
    load: () => import("@/app/api/projects/[id]/workbooks/route"),
  },
  {
    path: "/api/projects/deliverables/export",
    methods: { GET: { file: true, guard: "withSession" } },
    load: () => import("@/app/api/projects/deliverables/export/route"),
  },
  {
    path: "/api/projects/deliverables/progress",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/projects/deliverables/progress/route"),
  },
  {
    path: "/api/projects/deliverables/report",
    methods: { GET: { file: true, guard: "withSession" } },
    load: () => import("@/app/api/projects/deliverables/report/route"),
  },
  {
    path: "/api/projects/deliverables/report/scope",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/projects/deliverables/report/scope/route"),
  },
  {
    path: "/api/projects/deliverables",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/projects/deliverables/route"),
  },
  {
    path: "/api/projects/goals",
    methods: { GET: { query: ["projectId"], guard: "withSession" } },
    load: () => import("@/app/api/projects/goals/route"),
  },
  {
    path: "/api/projects/message-attachments/[attachmentId]/file",
    methods: { GET: { query: ["download"], file: true } },
    load: () => import("@/app/api/projects/message-attachments/[attachmentId]/file/route"),
  },
  {
    path: "/api/projects/my-deliverables",
    methods: { GET: { query: ["limit"], guard: "withSession" } },
    load: () => import("@/app/api/projects/my-deliverables/route"),
  },
  {
    path: "/api/projects/performance/report",
    methods: { POST: { permissions: ["project:write"], guard: "withSession" } },
    load: () => import("@/app/api/projects/performance/report/route"),
  },
  {
    path: "/api/projects/performance",
    methods: {
      GET: {
        query: ["projectId", "from", "to"],
        permissions: ["project:write"],
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/projects/performance/route"),
  },
  {
    path: "/api/projects/performance/scope",
    methods: { GET: { permissions: ["project:write"], guard: "withSession" } },
    load: () => import("@/app/api/projects/performance/scope/route"),
  },
  {
    path: "/api/projects",
    methods: {
      GET: { query: ["status", "mine", "clientId", "page", "limit"], guard: "withSession" },
      POST: { permissions: ["project:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/projects/route"),
  },
  {
    path: "/api/projects/tasks",
    methods: { GET: { permissions: ["project:write"], guard: "withSession" } },
    load: () => import("@/app/api/projects/tasks/route"),
  },
  {
    path: "/api/projects/weekly-hours",
    methods: { GET: { query: ["week"], guard: "withSession" } },
    load: () => import("@/app/api/projects/weekly-hours/route"),
  },
  {
    path: "/api/recruitment/applicants/[id]/offer",
    methods: { POST: { permissions: ["recruitment:write"], guard: "withAuth" } },
    load: () => import("@/app/api/recruitment/applicants/[id]/offer/route"),
  },
  {
    path: "/api/recruitment/applicants/[id]/resume",
    methods: {
      GET: { file: true, permissions: ["recruitment:read"], guard: "withAuth" },
      POST: { upload: true, permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/applicants/[id]/resume/route"),
  },
  {
    path: "/api/recruitment/applicants/[id]",
    methods: {
      PATCH: { permissions: ["recruitment:write"], guard: "withAuth" },
      DELETE: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/applicants/[id]/route"),
  },
  {
    path: "/api/recruitment/applicants",
    methods: {
      GET: { query: ["jobId", "stage"], permissions: ["recruitment:read"], guard: "withAuth" },
      POST: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/applicants/route"),
  },
  {
    path: "/api/recruitment/applications/[id]",
    methods: {
      GET: { permissions: ["recruitment:read"], guard: "withAuth" },
      PATCH: { permissions: ["recruitment:write"], guard: "withAuth" },
      DELETE: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/applications/[id]/route"),
  },
  {
    path: "/api/recruitment/applications",
    methods: {
      GET: {
        query: ["page", "limit", "status", "mode", "q"],
        permissions: ["recruitment:read"],
        guard: "withAuth",
      },
    },
    load: () => import("@/app/api/recruitment/applications/route"),
  },
  {
    path: "/api/recruitment/interviews/[id]",
    methods: {
      PATCH: { permissions: ["recruitment:write"], guard: "withAuth" },
      DELETE: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/interviews/[id]/route"),
  },
  {
    path: "/api/recruitment/interviews",
    methods: {
      GET: { query: ["applicantId"], permissions: ["recruitment:read"], guard: "withAuth" },
      POST: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/interviews/route"),
  },
  {
    path: "/api/recruitment/jobs/[id]",
    methods: {
      GET: { permissions: ["recruitment:read"], guard: "withAuth" },
      PATCH: { permissions: ["recruitment:write"], guard: "withAuth" },
      DELETE: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/jobs/[id]/route"),
  },
  {
    path: "/api/recruitment/jobs/generate",
    methods: { POST: { guard: "withSession" } },
    load: () => import("@/app/api/recruitment/jobs/generate/route"),
  },
  {
    path: "/api/recruitment/jobs",
    methods: {
      GET: { query: ["status"], permissions: ["recruitment:read"], guard: "withAuth" },
      POST: { permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/recruitment/jobs/route"),
  },
  {
    path: "/api/referrals/[id]",
    methods: {
      PATCH: { body: "{ action?: string }", permissions: ["recruitment:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/referrals/[id]/route"),
  },
  {
    path: "/api/referrals/admin",
    methods: { GET: { permissions: ["recruitment:write"], guard: "withAuth" } },
    load: () => import("@/app/api/referrals/admin/route"),
  },
  {
    path: "/api/referrals/roles",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/referrals/roles/route"),
  },
  {
    path: "/api/referrals",
    methods: {
      GET: { guard: "withSession" },
      POST: {
        body: "{ fullName: string, email: string, phone?: string, resumeUrl: any, linkedIn: any, careerRoleId: string, note?: string }",
        guard: "withSession",
      },
    },
    load: () => import("@/app/api/referrals/route"),
  },
  {
    path: "/api/resignations/[id]/review",
    methods: {
      POST: { body: '{ action: "APPROVE" | "REJECT", note?: string }', guard: "withErrorHandler" },
    },
    load: () => import("@/app/api/resignations/[id]/review/route"),
  },
  {
    path: "/api/resignations/[id]",
    methods: { DELETE: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/resignations/[id]/route"),
  },
  {
    path: "/api/resignations/review/count",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/resignations/review/count/route"),
  },
  {
    path: "/api/resignations/review",
    methods: { GET: { query: ["page", "limit"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/resignations/review/route"),
  },
  {
    path: "/api/resignations",
    methods: {
      GET: { guard: "withErrorHandler" },
      POST: {
        body: "{ reason?: string, requestedLastWorkingDate?: string }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/resignations/route"),
  },
  {
    path: "/api/roles/[id]",
    methods: {
      GET: { permissions: ["role:read"], guard: "withAuth" },
      PATCH: { permissions: ["role:write"], guard: "withAuth" },
      DELETE: { permissions: ["role:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/roles/[id]/route"),
  },
  {
    path: "/api/roles",
    methods: {
      GET: { permissions: ["role:read"], guard: "withAuth" },
      POST: { permissions: ["role:write"], guard: "withAuth" },
    },
    load: () => import("@/app/api/roles/route"),
  },
  {
    path: "/api/seo/sites",
    methods: { GET: { permissions: ["project:write"], guard: "withAuth" } },
    load: () => import("@/app/api/seo/sites/route"),
  },
  {
    path: "/api/stock/employees",
    methods: { GET: { query: ["q"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/stock/employees/route"),
  },
  {
    path: "/api/stock/import",
    methods: { POST: { body: "{ items: any, issues: any }", guard: "withErrorHandler" } },
    load: () => import("@/app/api/stock/import/route"),
  },
  {
    path: "/api/stock/issues/[id]",
    methods: { PATCH: { guard: "withErrorHandler" }, DELETE: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/stock/issues/[id]/route"),
  },
  {
    path: "/api/stock/issues/bulk",
    methods: { POST: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/stock/issues/bulk/route"),
  },
  {
    path: "/api/stock/issues",
    methods: {
      GET: { query: ["q", "itemId", "unlinked", "page", "limit"], guard: "withErrorHandler" },
      POST: {
        body: "{ itemId: string, holderName: string, employeeId?: string, quantity: number, issuedOn: any, notes?: string }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/stock/issues/route"),
  },
  {
    path: "/api/stock/items/[id]",
    methods: { PATCH: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/stock/items/[id]/route"),
  },
  {
    path: "/api/stock/items",
    methods: {
      GET: { guard: "withErrorHandler" },
      POST: {
        body: "{ name: string, pricePerPiece?: number, purchasedQty?: number, notes?: string }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/stock/items/route"),
  },
  {
    path: "/api/stock/register",
    methods: {
      GET: { query: ["q", "itemId", "unlinked", "page", "limit"], guard: "withErrorHandler" },
      PATCH: {
        body: "{ holderName: string, employeeId: string, issuedOn: any, cells: any }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/stock/register/route"),
  },
  {
    path: "/api/tasks/[id]/checklist/[itemId]",
    methods: { PATCH: { guard: "withSession" }, DELETE: { guard: "withSession" } },
    load: () => import("@/app/api/tasks/[id]/checklist/[itemId]/route"),
  },
  {
    path: "/api/tasks/[id]/checklist",
    methods: { GET: { guard: "withSession" }, POST: { guard: "withSession" } },
    load: () => import("@/app/api/tasks/[id]/checklist/route"),
  },
  {
    path: "/api/tasks/[id]/comments/[commentId]",
    methods: { DELETE: { guard: "withSession" } },
    load: () => import("@/app/api/tasks/[id]/comments/[commentId]/route"),
  },
  {
    path: "/api/tasks/[id]/comments",
    methods: { GET: { guard: "withSession" }, POST: { guard: "withSession" } },
    load: () => import("@/app/api/tasks/[id]/comments/route"),
  },
  {
    path: "/api/tasks/[id]",
    methods: {
      PATCH: { permissions: ["project:write"], guard: "withSession" },
      DELETE: { permissions: ["project:write"], guard: "withSession" },
    },
    load: () => import("@/app/api/tasks/[id]/route"),
  },
  {
    path: "/api/tasks/[id]/timeline",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/tasks/[id]/timeline/route"),
  },
  {
    path: "/api/tasks",
    methods: {
      GET: {
        query: ["mine", "scope", "status"],
        permissions: ["project:write"],
        guard: "withSession",
      },
      POST: { permissions: ["project:write"], guard: "withSession" },
    },
    load: () => import("@/app/api/tasks/route"),
  },
  {
    path: "/api/wfh/apply/preview",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/wfh/apply/preview/route"),
  },
  {
    path: "/api/wfh/eligibility",
    methods: { GET: { guard: "withErrorHandler" } },
    load: () => import("@/app/api/wfh/eligibility/route"),
  },
  {
    path: "/api/wfh/my-team",
    methods: { GET: { query: ["scope", "status", "page", "limit"], guard: "withErrorHandler" } },
    load: () => import("@/app/api/wfh/my-team/route"),
  },
  {
    path: "/api/wfh/requests/[id]",
    methods: {
      PATCH: {
        body: '{ action: "CANCEL" | "APPROVE" | "REJECT", rejectionReason?: string }',
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/wfh/requests/[id]/route"),
  },
  {
    path: "/api/wfh/requests",
    methods: {
      GET: {
        query: ["status", "employeeId", "from", "to", "page", "limit"],
        guard: "withErrorHandler",
      },
      POST: {
        body: "{ date: string, endDate?: string, reason?: string, isEmergency?: boolean, emailSubject?: string, emailBody?: string }",
        guard: "withErrorHandler",
      },
    },
    load: () => import("@/app/api/wfh/requests/route"),
  },
  {
    path: "/api/work-reports",
    methods: { GET: { file: true, guard: "withSession" } },
    load: () => import("@/app/api/work-reports/route"),
  },
  {
    path: "/api/work-reports/scope",
    methods: { GET: { guard: "withSession" } },
    load: () => import("@/app/api/work-reports/scope/route"),
  },
]
