// Public API for the marketing feature. Only these are imported from app/.
export { MarketingHeader } from "./components/marketing-header"
export { MarketingFooter } from "./components/marketing-footer"
export { StructuredData } from "./components/structured-data"
export { SpotlightCursor } from "./components/fx"

// Sections (in page order)
export { Hero } from "./components/sections/hero"
export { MarqueeStrip } from "./components/sections/marquee-strip"
export { StatsBand } from "./components/sections/stats-band"
export { PlatformIntro } from "./components/sections/platform-intro"
export { BentoOverview } from "./components/sections/bento-overview"
export { SpotlightHr } from "./components/sections/spotlight-hr"
export { SpotlightAttendance } from "./components/sections/spotlight-attendance"
export { SpotlightLeave } from "./components/sections/spotlight-leave"
export { SpotlightPayroll } from "./components/sections/spotlight-payroll"
export { SpotlightProjects } from "./components/sections/spotlight-projects"
export { SpotlightRecruitment } from "./components/sections/spotlight-recruitment"
export { SpotlightClientPortal } from "./components/sections/spotlight-client-portal"
export { SpotlightComms } from "./components/sections/spotlight-comms"
export { SpotlightSeo } from "./components/sections/spotlight-seo"
export { HowItConnects } from "./components/sections/how-it-connects"
export { Benefits } from "./components/sections/benefits"
export { WhyDnms } from "./components/sections/why-dnms"
export { SecuritySection } from "./components/sections/security"
export { Philosophy } from "./components/sections/philosophy"
export { Faq } from "./components/sections/faq"
export { Closing } from "./components/sections/closing"
